<?php

namespace App\Tests\Api\Plant;

use App\Repository\SpeciesRepository;
use App\Tests\Api\AbstractApiTestCase;

/**
 * Functional tests for POST /api/plants.
 *
 * Fixture state (reloaded before EACH test — POST modifies the database):
 *   - admin@plant.dev  → ROLE_ADMIN, 0 plants
 *   - user1@plant.dev  → ROLE_USER,  3 plants
 *   - user2@plant.dev  → ROLE_USER,  2 plants
 *   - 5 species: Monstera, Pothos, Ficus, Succulent, Orchidée
 */
class PostTest extends AbstractApiTestCase
{
    // -------------------------------------------------------------------------
    // Setup
    // -------------------------------------------------------------------------

    /**
     * Unlike GetCollectionTest, fixtures are reloaded before EVERY test here.
     * POST creates data: without a reset, plants created in test N accumulate
     * and would break count assertions in test N+1.
     */
    protected function setUp(): void
    {
        parent::setUp(); // boots kernel, sets $this->client
        $this->loadFixtures();
    }

    /**
     * Builds a valid PlantInput payload.
     *
     * Species IDs are auto-generated by PostgreSQL and cannot be hardcoded.
     * We fetch the Monstera species from the container and build its IRI
     * dynamically to guarantee a valid reference regardless of sequence state.
     *
     * Callers can override individual fields to test specific validation rules.
     *
     * @param array<string, mixed> $overrides
     *
     * @return array<string, mixed>
     */
    private function buildPayload(array $overrides = []): array
    {
        $species = static::getContainer()
            ->get(SpeciesRepository::class)
            ->findOneBy(['commonName' => 'Monstera']);

        return array_merge([
            'name' => 'Mon Cactus Test',
            'wateringFrequencyDays' => 14,
            'lastWateredAt' => '2026-07-01T10:00:00+00:00',
            'acquiredAt' => '2026-01-01T00:00:00+00:00',
            'species' => '/api/species/'.$species->getId(),
            'notes' => 'Test notes',
        ], $overrides);
    }

    // -------------------------------------------------------------------------
    // Authentication guard
    // -------------------------------------------------------------------------

    /**
     * Without a token, the JWT firewall must reject before any business logic.
     */
    public function testUnauthenticatedRequestReturns401(): void
    {
        $result = $this->jsonRequest('POST', '/api/plants', null, $this->buildPayload());

        $this->assertSame(401, $result['status']);
    }

    // -------------------------------------------------------------------------
    // Happy path
    // -------------------------------------------------------------------------

    /**
     * A valid payload from an authenticated user must create the plant
     * and return a 201 with the full PlantOutput structure.
     *
     * Validates that PlantProcessor correctly maps PlantInput → Plant → PlantOutput.
     */
    public function testValidPayloadReturns201WithPlantOutput(): void
    {
        $token = $this->getToken('user1@plant.dev');
        $result = $this->jsonRequest('POST', '/api/plants', $token, $this->buildPayload());

        $this->assertSame(201, $result['status'], $result['body']);

        $plant = $result['data'];
        $this->assertArrayHasKey('id', $plant);
        $this->assertArrayHasKey('name', $plant);
        $this->assertArrayHasKey('wateringFrequencyDays', $plant);
        $this->assertArrayHasKey('lastWateredAt', $plant);
        $this->assertArrayHasKey('acquiredAt', $plant);
        $this->assertArrayHasKey('speciesId', $plant);
        $this->assertArrayHasKey('speciesCommonName', $plant);
        $this->assertArrayHasKey('speciesLatinName', $plant);
        $this->assertArrayHasKey('createdAt', $plant);
        $this->assertArrayHasKey('updatedAt', $plant);

        $this->assertSame('Mon Cactus Test', $plant['name']);
        $this->assertSame(14, $plant['wateringFrequencyDays']);
        $this->assertSame('Monstera', $plant['speciesCommonName']);
    }

    /**
     * The owner is assigned automatically by PlantProcessor from the
     * authenticated user — it is never sent by the client.
     *
     * We verify ownership indirectly: after user1 creates a plant, user2
     * must receive 404 when requesting that same plant by ID.
     * PlantProvider filters by owner, so a 404 proves isolation is enforced.
     */
    public function testCreatedPlantIsOnlyVisibleToItsOwner(): void
    {
        $tokenUser1 = $this->getToken('user1@plant.dev');
        $tokenUser2 = $this->getToken('user2@plant.dev');

        $postResult = $this->jsonRequest('POST', '/api/plants', $tokenUser1, $this->buildPayload());
        $this->assertSame(201, $postResult['status'], $postResult['body']);

        $plantId = $postResult['data']['id'];

        $getResult = $this->jsonRequest('GET', '/api/plants/'.$plantId, $tokenUser2);
        $this->assertSame(404, $getResult['status']);
    }

    // -------------------------------------------------------------------------
    // Business logic errors (400)
    // -------------------------------------------------------------------------

    /**
     * PlantProcessor resolves species by extracting the ID from the IRI string
     * via basename(). If no species exists with that ID, it throws a 400.
     * This tests the processor's explicit guard, not the validator.
     */
    public function testNonExistentSpeciesReturns400(): void
    {
        $token = $this->getToken('user1@plant.dev');
        $payload = $this->buildPayload(['species' => '/api/species/99999']);
        $result = $this->jsonRequest('POST', '/api/plants', $token, $payload);

        $this->assertSame(400, $result['status'], $result['body']);
    }

    // -------------------------------------------------------------------------
    // Validation errors (422)
    // -------------------------------------------------------------------------

    /**
     * name is annotated @NotBlank — sending it empty or absent must return 422.
     */
    public function testMissingNameReturns422(): void
    {
        $token = $this->getToken('user1@plant.dev');
        $payload = $this->buildPayload(['name' => '']);
        $result = $this->jsonRequest('POST', '/api/plants', $token, $payload);

        $this->assertSame(422, $result['status'], $result['body']);
    }

    /**
     * wateringFrequencyDays is annotated @Positive — zero and negative
     * values must be rejected.
     */
    public function testNonPositiveWateringFrequencyReturns422(): void
    {
        $token = $this->getToken('user1@plant.dev');

        $resultZero = $this->jsonRequest(
            'POST', '/api/plants', $token,
            $this->buildPayload(['wateringFrequencyDays' => 0]),
        );
        $this->assertSame(422, $resultZero['status'], $resultZero['body']);

        $resultNegative = $this->jsonRequest(
            'POST', '/api/plants', $token,
            $this->buildPayload(['wateringFrequencyDays' => -5]),
        );
        $this->assertSame(422, $resultNegative['status'], $resultNegative['body']);
    }

    /**
     * lastWateredAt and acquiredAt are annotated @NotNull.
     * Omitting them must return 422.
     */
    public function testMissingRequiredDatesReturn422(): void
    {
        $token = $this->getToken('user1@plant.dev');

        $resultNoLastWatered = $this->jsonRequest(
            'POST', '/api/plants', $token,
            $this->buildPayload(['lastWateredAt' => null]),
        );
        $this->assertSame(422, $resultNoLastWatered['status'], $resultNoLastWatered['body']);

        $resultNoAcquired = $this->jsonRequest(
            'POST', '/api/plants', $token,
            $this->buildPayload(['acquiredAt' => null]),
        );
        $this->assertSame(422, $resultNoAcquired['status'], $resultNoAcquired['body']);
    }

    /**
     * name has @Length(max: 255) — a 256-character string must return 422.
     */
    public function testNameExceedingMaxLengthReturns422(): void
    {
        $token = $this->getToken('user1@plant.dev');
        $payload = $this->buildPayload(['name' => str_repeat('a', 256)]);
        $result = $this->jsonRequest('POST', '/api/plants', $token, $payload);

        $this->assertSame(422, $result['status'], $result['body']);
    }
}
